version: "2"
services:
  jenkins_data:
    image: jenkins/jenkins:lts
    entrypoint: /bin/true
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes_from:
      - jenkins_data
  nexus:
    image: sonatype/nexus:oss
    ports:
      - "8081:8081"

